### ISSUE TITLE
Failed to fetch info for package apr-util-ldap.x86_64

### ISSUE THREAD

**Issue by lebramicka** [rocky-linux/rocky-tools#85] opened 2021-07-20 17:27 UTC
Dear All,

I have the following error with the migrate script : 

Removing dnf cache
Preparing to migrate CentOS Linux 8 to Rocky Linux 8.

Determining repository names for CentOS Linux 8.Importing GPG key 0x307EA071:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)"
 Fingerprint: 7F92 E05B 3109 3BEF 5A3C 2D38 FEEA 9169 307E A071
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg

Failed to fetch info for package apr-util-ldap.x86_64.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

Env : 
CentOS Linux release 8.4.2105
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
CentOS Linux release 8.4.2105
CentOS Linux release 8.4.2105

Any idea ?

Thanks

**Comment by lebramicka** [comment] 2021-07-21 07:27
I need in fact to simply enter : y + Enter in order to validate the key.

**Comment by pajamian** [comment] 2021-07-21 10:28
I'm reopening this because it's a bug that you have to press "y" at that stage.

**Comment by Wolf-DK** [comment] 2021-07-21 18:58
This provided me with the solution to get past the error (many thanks).
You may want to at least add the solution to "known issues":
To type "y" then enter" if the script stops with the message:
```
 .Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
```

/Wolf

**Comment by pajamian** [comment] 2021-07-22 04:35
Thanks,
It means that there is a dnf command in the script that is missing the -y switch, probably because it wasn't thought to be needed for that particular command.

**Comment by Wolf-DK** [comment] 2021-07-22 09:35
Here is the complete log, from before I entered "y" with Enter.
Here I just hit Enter every time the script stopped until it actually quit:

`
Removing dnf cache
Preparing to migrate CentOS Linux 8 to Rocky Linux 8.

Determining repository names for CentOS Linux 8.Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
Error: Failed to download metadata for repo 'remi-modular': repomd.xml GPG signature verification error: Bad GPG signature

Failed to fetch info for package apr-util-ldap.x86_64.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 .Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
Error: Failed to download metadata for repo 'remi-modular': repomd.xml GPG signature verification error: Bad GPG signature

Failed to fetch info for package pacemaker-doc.noarch.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 .Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
Error: Failed to download metadata for repo 'remi-modular': repomd.xml GPG signature verification error: Bad GPG signature

Failed to fetch info for package rootfiles.noarch.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 .Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
Error: Failed to download metadata for repo 'remi-modular': repomd.xml GPG signature verification error: Bad GPG signature

Failed to fetch info for package epel-release.noarch.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 .Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
Error: Failed to download metadata for repo 'remi-modular': repomd.xml GPG signature verification error: Bad GPG signature

Failed to fetch info for package libaec-devel.x86_64.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.



Found the following repositories which map from CentOS Linux 8 to Rocky Linux 8:
CentOS Linux 8  Rocky Linux 8
                appstream
                ha
                baseos
                extras
                powertools

Getting system package names for CentOS Linux 8Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
Error: Failed to download metadata for repo 'remi-modular': repomd.xml GPG signature verification error: Bad GPG signature

Failed to fetch info for repository .

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

`

**Comment by suchagoodguy** [comment] 2021-07-22 14:39
`Failed to fetch info for package apr-util-ldap.x86_64.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 A log of this installation can be found at /var/log/migrate2rocky.log`

This is what I get every time when I press Ctrl+C. Otherwise it will last forever.

**Comment by luigirosa** [comment] 2021-07-25 07:24
Same bug here.
Fixed by pressing Y and Enter

```
Determining repository names for CentOS Stream 8.Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
y
Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
y

```

**Comment by suchagoodguy** [comment] 2021-07-26 06:47
Lucky you! I haven't been asked for confirmations at all.

**Comment by suchagoodguy** [comment] 2021-07-26 06:52
Have tried to press Y and Enter and it worked.

**Comment by pajamian** [comment] 2021-08-14 04:52
@lebramicka @Wolf-DK @suchagoodguy can you test with this version, please?
https://github.com/pajamian/rocky-tools/blob/issue85/migrate2rocky/migrate2rocky.sh

**Comment by aminvakil** [comment] 2021-08-14 12:53
I faced this problem when migrating another CentOS 8 operating system:
```
Importing GPG key 0x5F11735A:
 Userid     : "Remi's RPM repository <remi@remirepo.net>"
 Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
```
Stuck and failure here.

And I can confirm https://github.com/pajamian/rocky-tools/blob/issue85/migrate2rocky/migrate2rocky.sh fixed my issue, thanks @pajamian!

**Comment by pajamian** [comment] 2021-08-15 08:39
Merged in PR #102

**Closed by pajamian** 2021-08-15 08:39 UTC
