### ISSUE TITLE
Bug with language not changed.

### ISSUE THREAD

**Issue by alonezw** [rocky-linux/rocky-tools#65] opened 2021-07-01 16:48 UTC
When i trying to migrate from CentOS to Rocky, an error occurs: https://pastebin.com/LubK24hY

Definition "export LANG = en_US.UTF-8"  in the script is clearly not enough.

How fixed:
**LANGUAGE=en_US ./migrate2rocky.sh -r**

Result is successful: https://pastebin.com/EZTcPR8i

Please add "export LANGUAGE=en_US" to the script.

**Comment by pajamian** [comment] 2021-07-03 06:19
Thanks for the report.  I'm changing it to:
`export LC_ALL=en_US.UTF-8 LANGUAGE=en_US`
...this should force the issue.

**Comment by pajamian** [comment] 2021-07-03 08:33
Can you check PR #67 and make sure that it fixes your issue?
https://raw.githubusercontent.com/rocky-linux/rocky-tools/15c75aba490356d69ed64ee3b244a28ecd2939c9/migrate2rocky/migrate2rocky.sh

**Comment by pajamian** [comment] 2021-07-13 11:11
Merged since testing did not show a regression.  If this does not fix the issue let me know.

**Closed by pajamian** 2021-07-13 11:11 UTC
